env: dev-local
prom_url: https://prometheus.u-cloudsolutions.xyz
step: 60s
rate_window: 5m
aliases_enabled: true
aliases_file: app/config/aliases.yaml
recipes_file: app/config/metric_recipes.yaml
